### ISSUE TITLE
nest js 文件上传那部分的说明有点少，能不能给一个详细点的例子呢

### ISSUE THREAD

**Issue by Owen-Zhang** [nestcn/docs#27]

**Comment by zuohuadong** [comment]
文档目前只遵从官方翻译。

一点经验：
对于文件上传，我们并没有使用 nest.js 的上传机制，而是使用了 云存储，做了异步表单上传（文件不经过服务器），所以后端只需要很少的带宽保证接口即可。
前端的静态资源文件，也建议一并放到CDN
