### ISSUE TITLE
机翻文档？

### ISSUE THREAD

**Issue by yuu2lee4** [nestcn/docs#30]
好多地方都读不通顺

**Comment by zuohuadong** [comment]
参考bing 和 谷歌 的机翻+校对

**Comment by chenyulun** [comment]
受不了，不知所云，还不如去看官方文档

**Comment by zuohuadong** [comment]
@chenyulun

nest 有许多新的概念，如果没有学过spring ，确实会看不懂。

**Comment by chenyulun** [comment]
为什么我能看懂angular6，你这个我就看不懂

**Comment by zuohuadong** [comment]
@chenyulun 没有必然关系。
公司之前做java 的也能看懂。

翻译中肯定会存在纰漏，如果有问题，欢迎提交PR～
